# Faster builds https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false
dist: trusty

language: java

jdk:
- oraclejdk8

# For GUI based tests using xvfb
#before_script:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - sleep 3

before_install:
  - echo "Download Maven ${CUSTOM_MVN_VERION}....";
  - wget https://archive.apache.org/dist/maven/maven-3/${CUSTOM_MVN_VERION}/binaries/apache-maven-${CUSTOM_MVN_VERION}-bin.tar.gz
  - tar xzvf apache-maven-${CUSTOM_MVN_VERION}-bin.tar.gz
  - export M2_HOME=`pwd`/apache-maven-${CUSTOM_MVN_VERION}
  - export PATH=$M2_HOME/bin:$PATH
  - mvn -v

script: "mvn test verify"

# cache the build tool's caches
cache:
  directories:
    - "$HOME/.m2"

# After the build, run the script that will collect JaCoCo statistics
# It uses the third-party service https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - if [ "$TRAVIS_BRANCH" != "master" ]; then openssl aes-256-cbc -pass pass:$ENC_PASSWORD
#    -in .travis/sign.asc.enc -out .travis/sign.asc -d; gpg -q --fast-import .travis/sign.asc;
#    mvn deploy --settings .travis.settings.xml -DskipTests=true; chmod +x .travis/upload-build.sh; .travis/upload-build.sh; fi

# Send a notification to your email id, if the assembly has dropped
notifications:
  email:
    recipients:
      - singrahu@gmail.com
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3030952ce142f06ee5b3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
  global:
    - CUSTOM_MVN_VERION="3.6.1"
    # CodeCov.io API token
    - secure: cud+2qClMMkbZYcyXCKsZyYXHQQIQO+vDhaeenouy9RrZO+LjleoHgPDlBjEF0DVj7IvjyjjpLn+f2QDMRIufejU7K49Etj9ktY0iKsqFZ4kuK3o+5qtmrht6JDJs4EiLFJZ+QYdY1KTHS87cnQuYt7xmG5AlQYAOWhOkYGwSA50z2+iVo81ZdG+C92zh7cHRhS3mnH5R76spmX82Gtjs/mxZJc1WR5je4O99fKWDiNPIDIK4EXLX+LeMwFu62iz0pV/VvtahMfv1L7bq9h4xgKMlweFGP0zsluQgbmfPZLW2wCU+MyOJt63KsJlG2UpPge4+X1upDQ+Xj+ii8gUzP9AbxeMn8OZKjsg7xDOsuXxchsmEhTfGoIT1QaMfZJOU7aSActPg8XmLAfFPKO65HrviEnrp6xitc9RfdUtu5GdJNHJD43QNEregPt6mjaSPqMN0eDV/T0HMU91FBqfEoAWMEhz5NAH4KxP7Lu2QSnoEyeBV39Ve1FM1r949cdPKEEUa3XyZvshoiK55hHlCs1VTgm9rEvAV4/Jcbf4CwbKvdyinWEb6/hirgxZHT8zyvOWTa9QIP4lEFBeMALLtxtIb/XTYOyx2AA4sZsR/mfyCnjqa/+j5B/iuD3uBGN685bjocZ1Ta4TYKnoXU7pA5tQzz3mY8Vyjz5q/N/5eK8=
